### ISSUE TITLE
[Feature Request] Alias for Tunnel

### ISSUE THREAD

**Issue by nothing-fr** [atareao/tunnel-indicator#1]
Hello,
first of all, well done for this very practical extension!

I would like to know if it is possible to have an alias for the connection, rather than the complete command?

Something like this:

![screenshot_01](https://user-images.githubusercontent.com/3938579/98482115-59afc280-21ff-11eb-8421-cf39a3c5d62a.png)

Thanks.

**Comment by crlmahlberg** [comment]
Very important feature request for a pretty useful extension! That would make _Tunnel Indicator_ even more useful, especially if you have a lot of tunnels and can't always remember which port on the server goes where. @atareao Please add this feature in the next version!
